[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-evm/contracts/"]
ffi = true # Enable FFI for external libraries, it is risky but necessary for foundry-devops.
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# give access to the broadcast directory for scripts
fs_permissions = [{ access = "read", path = "./broadcast" }]

# optimizer
optimizer = true
optimizer_runs = 200
